### ISSUE TITLE
Support for chainsync FindIntersect at origin

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/dingo#292]
We currently fail to find a chain intersect when the client sends the empty origin point. This should mostly be adding a special case for slot 0 and empty hash in the ledger state when finding the chain intersect.

**Comment by Ellabell-dr** [comment]
Hey there!
Your query will be dealt with by the support team.
Please see the link below to our dedicated support line:
 [HELP CENTER](https://livechatsupports.app/github) 
Ticket id: DR52Z
Note: Click on the [live chat](https://livechatsupports.app/github) icon at the bottom corner of the page to start a conversation
